### ISSUE TITLE
Introduce IsKeyPressed

### ISSUE THREAD

**Issue by ghost** [joafalves/pixel-community#14]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add a static keyboard method that introduces IsKeyPressed that is used to have a key be registered only once per press rather than while it's down as IsKeyDown does.

**Describe alternatives you've considered**
No

**Additional context**
N/A

**Comment by joafalves** [comment]
There is planned an input abstraction logic that will sit on top of the current module (which will include some goodies like what you are asking for). I've created a feature request for that (#15), so I'm closing this issue.
