### ISSUE TITLE
Roadmap and community?

### ISSUE THREAD

**Issue by ghost** [joafalves/pixel-community#2]
Hi! I'm really interested in this framework! Looks really amazing so far and it's always great to see more potential frameworks for JVM. I love what you're doing here and the inspiration you took from XNA. I'm rooting for this to carry on.

Wanted to ask if you by chance you have any roadmap on what is done, what is still in progress and planned for the future for this framework? But also if there is any other way to reach you or if there is a community for this project?

Thanks!

**Comment by joafalves** [comment]
Hey there! 

First of all, thanks for your interest. I've been working ocasionally on this for some time now - mostly for mocks & some small gigs. I've used XNA extensively in the past (developed [Gibbo2D](https://www.moddb.com/engines/gibbo2d)) and I was missing a "XNA-like" approach on the JVM - and so this project was created.

Regarding your questions:
1º - Great timing! On the past weeks I've been focused on puting out a stable release of the features already available (v0.6.0), which should be ready in January - public roadmaps will follow around the same time. 
2º - Besides this Github page, there is no other community around this project yet (I haven't published it anywhere - if you don't mind asking, where did you learn about it?).
3º - Currently there is no "official" page for the features available, but if you are interested, please check the examples on the '/demos' folder (on the 'devel' branch) - you can find some practical examples of the framework:

* (demos root folder) https://github.com/joafalves/pixel-community/tree/devel/demos
* (learning examples) https://github.com/joafalves/pixel-community/tree/devel/demos/learning/src/main/java/org/pixel/demo/learning

If you have any extra questions (or if you want to contribute) you can reach out directly to me at joao.cpp.sca@gmail.com

**Comment by ghost** [comment]
Hey thanks for responding!

Personally this type of framework is what I've been searching for. I have nothing against LibGDX, but for whatever reason I find it difficult to get into (especially when using Kotlin & LibKTX)...

1 - This is great! I'm looking forward to the stable release!

2 - Atta shame have to say. I think the framework has potential! Will you plan to one day perhaps create a discord server for the framework when you feel like it's ready? I personally found it by searching for game frameworks on Github as sadly many out there just didn't fit my purpose e.g. KorGE (framework written in pure Kotlin) has many many issues that renders it unusable for me. miniGDX (another kotlin framework) forces you to write in ECS which I don't feel ready to jump into and haven't been updated in a while so I don't know if it's still alive or not and there's no way of communicating with the creator.

3 - Thank you, will do. But was also wondering if you will plan to throw the framework on Gradle to make using it much easier?

Thanks!

**Comment by joafalves** [comment]
There is a discord room already available, although it was not published yet (but feel free to join @ https://discord.gg/Wf3VsUcM)

Regarding your third question, yes, it's also planned for early 2022.

In addition, I've started to write the WIKI -> https://github.com/joafalves/pixel-community/wiki/1.-Getting-Started (**WIP**)

**Comment by ghost** [comment]
Thanks! That answered all of my questions so I guess I can close it!
